### ISSUE TITLE
Error when training NN on BNP Paribas kaggle dataset

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#142]
```py
Traceback (most recent call last):
  File "examples/scripts/binary_classifier_BNP_GoldenFeatures.py", line 22, in <module>
    automl.fit(X, y)
  File "/home/piotr/sandbox/mljar-supervised/supervised/automl.py", line 1130, in fit
    raise e
  File "/home/piotr/sandbox/mljar-supervised/supervised/automl.py", line 1112, in fit
    self.train_model(params)
  File "/home/piotr/sandbox/mljar-supervised/supervised/automl.py", line 572, in train_model
    mf.train(model_path)
  File "/home/piotr/sandbox/mljar-supervised/supervised/model_framework.py", line 144, in train
    learner.fit(X_train, y_train, X_validation, y_validation, log_to_file)
  File "/home/piotr/sandbox/mljar-supervised/supervised/algorithms/nn.py", line 143, in fit
    self.model.fit(X, y, batch_size=batch_size, epochs=self.rounds, verbose=False)
  File "/home/piotr/sandbox/mljar-supervised/venv_mljs/lib/python3.6/site-packages/keras/engine/training.py", line 1154, in fit
    batch_size=batch_size)
  File "/home/piotr/sandbox/mljar-supervised/venv_mljs/lib/python3.6/site-packages/keras/engine/training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "/home/piotr/sandbox/mljar-supervised/venv_mljs/lib/python3.6/site-packages/keras/engine/training_utils.py", line 145, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected dense_1_input to have shape (231,) but got array with shape (230,)

```

**Comment by pplonski** [comment]
Can't reproduce the issue with the current code from `master`.
