### ISSUE TITLE
Missing Golden Features produces error

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#261]
When there are only categoricals values Golden Featuers are not created. But there are still some models tried with Golden Features. This produces following error:

```py

Golden Features not created due to error (please check errors.md).
Traceback (most recent call last):
  File "/bench/frameworks/mljarsupervised/venv/lib/python3.6/site-packages/supervised/base_automl.py", line 850, in _fit
    trained = self.train_model(params)
  File "/bench/frameworks/mljarsupervised/venv/lib/python3.6/site-packages/supervised/base_automl.py", line 283, in train_model
    mf.train(model_path)
  File "/bench/frameworks/mljarsupervised/venv/lib/python3.6/site-packages/supervised/model_framework.py", line 126, in train
    train_data["X"], train_data["y"]
  File "/bench/frameworks/mljarsupervised/venv/lib/python3.6/site-packages/supervised/preprocessing/preprocessing.py", line 177, in fit_and_transform
    self._golden_features.fit(X_train[numeric_cols], y_train)
  File "/bench/frameworks/mljarsupervised/venv/lib/python3.6/site-packages/supervised/preprocessing/goldenfeatures_transformer.py", line 114, in fit
    "Golden Features not created due to error (please check errors.md)."
supervised.exceptions.AutoMLException: Golden Features not created due to error (please check errors.md).
```

**Comment by pplonski** [comment]
I added more info to error message. And leave it as it is. Hard to come out with a better idea to handle it.
