### ISSUE TITLE
Error for 5_Default_CatBoost

### ISSUE THREAD

**Issue by ijeffking** [mljar/mljar-supervised#276]
Stop training after the first fold. Time needed to train on the first fold 821.0 seconds. The time estimate for training on all folds is larger than total_time_limit.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/supervised/base_automl.py", line 907, in _fit
    trained = self.train_model(params)
  File "/usr/local/lib/python3.6/dist-packages/supervised/base_automl.py", line 300, in train_model
    mf.train(model_path)
  File "/usr/local/lib/python3.6/dist-packages/supervised/model_framework.py", line 172, in train
    self.callbacks.on_learner_train_end()
  File "/usr/local/lib/python3.6/dist-packages/supervised/callbacks/callback_list.py", line 15, in on_learner_train_end
    cb.on_learner_train_end(logs)
  File "/usr/local/lib/python3.6/dist-packages/supervised/callbacks/total_time_constraint.py", line 44, in on_learner_train_end
    "Stop training after the first fold. "
supervised.exceptions.AutoMLException: Stop training after the first fold. Time needed to train on the first fold 821.0 seconds. The time estimate for training on all folds is larger than total_time_limit.

**Comment by pplonski** [comment]
Hi @ijeffking! I need to add strict time respecting for AutoML as it will be used in official openml/automlbenchmark That's why if the training after the first fold takes too long the whole training can be stopped.  The simplest solution will be to increase the `total_time_limit`. Sorry that it is not in docs, yet.

What is more, I added some ned features, like target encoding of categorical features. When the `total_time_limit` is long enough the alternative categorical encoding will be checked.

**Comment by pplonski** [comment]
I'm closing the issue as this is expected behavior.
