### ISSUE TITLE
Install errors 

### ISSUE THREAD

**Issue by nielsuit227** [mljar/mljar-supervised#302]
Get an error on both `pip install mljar-supervised` as well as `python setup.py install` after cloning. It might also be nice to add dependencies, I had to install MSVC14. 
I'm on Windows 10, Python 3.9.1, pip 20.3.3

Error logs:
```cli
>python setup.py install
 ...
Running wordcloud-1.7.0\setup.py -q bdist_egg --dist-dir C:\Users\NIELSU~1\AppData\Local\Temp\easy_install-fc3kkc0j\wordcloud-1.7.0\egg-dist-tmp-obtwg68v
UPDATING build\lib.win-amd64-3.9\wordcloud/_version.py
set build\lib.win-amd64-3.9\wordcloud/_version.py to '1.7.0'
query_integral_image.c
wordcloud/query_integral_image.c(2060): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
wordcloud/query_integral_image.c(2069): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
wordcloud/query_integral_image.c(16523): error C2039: 'tp_print': is not a member of '_typeobject'
C:\Users\Niels Uitterdijk\AppData\Local\Programs\Python\Python39\include\cpython/object.h(193): note: see declaration of '_typeobject'
wordcloud/query_integral_image.c(16528): error C2039: 'tp_print': is not a member of '_typeobject'
C:\Users\Niels Uitterdijk\AppData\Local\Programs\Python\Python39\include\cpython/object.h(193): note: see declaration of '_typeobject'
wordcloud/query_integral_image.c(16543): error C2039: 'tp_print': is not a member of '_typeobject'
C:\Users\Niels Uitterdijk\AppData\Local\Programs\Python\Python39\include\cpython/object.h(193): note: see declaration of '_typeobject'
wordcloud/query_integral_image.c(16556): error C2039: 'tp_print': is not a member of '_typeobject'
C:\Users\Niels Uitterdijk\AppData\Local\Programs\Python\Python39\include\cpython/object.h(193): note: see declaration of '_typeobject'
wordcloud/query_integral_image.c(17126): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
wordcloud/query_integral_image.c(17142): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
wordcloud/query_integral_image.c(18051): warning C4996: 'PyUnicode_FromUnicode': deprecated in 3.3
error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

```cli
>pip install mljar-supervised
Requirement already satisfied: mljar-supervised in c:\users\niels uitterdijk\appdata\local\programs\python\python39\lib\site-packages\mljar_supervised-0.7.20-py3.9.egg (0.7.20)
Requirement already satisfied: numpy>=1.18.5 in c:\users\niels uitterdijk\appdata\local\programs\python\python39\lib\site-packages (from mljar-supervised) (1.19.4)
Collecting mljar-supervised
  Using cached mljar-supervised-0.7.19.tar.gz (78 kB)
  Using cached mljar-supervised-0.7.18.tar.gz (78 kB)
  Using cached mljar-supervised-0.7.17.tar.gz (78 kB)
  Using cached mljar-supervised-0.7.16.tar.gz (77 kB)
  Using cached mljar-supervised-0.7.15.tar.gz (77 kB)
  Using cached mljar-supervised-0.7.14.tar.gz (77 kB)
  Using cached mljar-supervised-0.7.13.tar.gz (77 kB)
  Using cached mljar-supervised-0.7.12.tar.gz (76 kB)
  Using cached mljar-supervised-0.7.11.tar.gz (75 kB)
  Using cached mljar-supervised-0.7.10.tar.gz (74 kB)
  Using cached mljar-supervised-0.7.9.tar.gz (73 kB)
  Using cached mljar-supervised-0.7.8.tar.gz (72 kB)
  Using cached mljar-supervised-0.7.7.tar.gz (72 kB)
  Using cached mljar-supervised-0.7.6.tar.gz (72 kB)
  Using cached mljar-supervised-0.7.5.tar.gz (72 kB)
  Using cached mljar-supervised-0.7.4.tar.gz (71 kB)
  Using cached mljar-supervised-0.7.3.tar.gz (72 kB)
  Using cached mljar-supervised-0.7.2.tar.gz (70 kB)
  Using cached mljar-supervised-0.7.1.tar.gz (69 kB)
  Using cached mljar-supervised-0.7.0.tar.gz (69 kB)
  Using cached mljar-supervised-0.6.1.tar.gz (65 kB)
  Using cached mljar-supervised-0.6.0.tar.gz (61 kB)
  Using cached mljar-supervised-0.5.5.tar.gz (58 kB)
  Using cached mljar-supervised-0.5.4.tar.gz (58 kB)
  Using cached mljar-supervised-0.5.3.tar.gz (57 kB)
  Using cached mljar-supervised-0.5.2.tar.gz (55 kB)
  Using cached mljar-supervised-0.5.1.tar.gz (55 kB)
  Using cached mljar-supervised-0.5.0.tar.gz (55 kB)
  Using cached mljar-supervised-0.4.1.tar.gz (52 kB)
  Using cached mljar-supervised-0.4.0.tar.gz (52 kB)
  Using cached mljar-supervised-0.3.5.tar.gz (43 kB)
  Using cached mljar-supervised-0.3.4.tar.gz (43 kB)
  Using cached mljar-supervised-0.3.3.tar.gz (43 kB)
  Using cached mljar-supervised-0.3.2.tar.gz (43 kB)
  Using cached mljar-supervised-0.3.1.tar.gz (43 kB)
  Using cached mljar-supervised-0.3.0.tar.gz (43 kB)
  Using cached mljar-supervised-0.2.8.tar.gz (37 kB)
  Using cached mljar-supervised-0.2.7.tar.gz (37 kB)
  Using cached mljar-supervised-0.2.6.tar.gz (37 kB)
  Using cached mljar-supervised-0.2.5.tar.gz (37 kB)
  Using cached mljar-supervised-0.2.4.tar.gz (37 kB)
  Using cached mljar-supervised-0.2.3.tar.gz (37 kB)
  Using cached mljar-supervised-0.2.2.tar.gz (37 kB)
  Using cached mljar-supervised-0.2.1.tar.gz (36 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\niels uitterdijk\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Niels Uitterdijk\\AppData\\Local\\Temp\\pip-install-odt1d50h\\mljar-supervised_f80c0635c820463ab142bab154e98321\\setup.py'"'"'; __file__='"'"'C:\\Users\\Niels Uitterdijk\\AppData\\Local\\Temp\\pip-install-odt1d50h\\mljar-supervised_f80c0635c820463ab142bab154e98321\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Niels Uitterdijk\AppData\Local\Temp\pip-pip-egg-info-_wkqqlid'
         cwd: C:\Users\Niels Uitterdijk\AppData\Local\Temp\pip-install-odt1d50h\mljar-supervised_f80c0635c820463ab142bab154e98321\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Niels Uitterdijk\AppData\Local\Temp\pip-install-odt1d50h\mljar-supervised_f80c0635c820463ab142bab154e98321\setup.py", line 22, in <module>
        install_requires=open('requirements.txt').readlines(),
      File "c:\users\niels uitterdijk\appdata\local\programs\python\python39\lib\codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by pplonski** [comment]
@nielsuit227 thank you for reporting the problem. I didn't test the newest version with python 3.9. I remember that about 2-3 months ago the package didn't work with python 3.9 (there were missing packages). 

Could you try to run it with python 3.8? (3.6, 3.7, and 3.8 versions are supported).

**Comment by nielsuit227** [comment]
Ah, did not see that 3.9 was not supported yet. Just successfully installed on 3.8 :)

**Comment by pplonski** [comment]
Great! I'll be grateful for feedback about the package and the ML model performance.

The version `0.8.0` will be available soon with new nice improvements, like means features generation and boosting model on errors.
