### ISSUE TITLE
multi processor error

### ISSUE THREAD

**Issue by bacoco** [mljar/mljar-supervised#330]
Hi,
I am using win10 on an 768Gb RAM with 36 cores so 72 logical precessors but when tryinf autoML() i have this error :
Thanks

: 
There are samples with missing target values in the data which will be excluded for further analysis
AutoML directory: automl
The task is regression with evaluation metric rmse
AutoML will use algorithms: ['Baseline', 'Linear', 'Decision Tree', 'Random Forest', 'Xgboost', 'Neural Network']
AutoML will ensemble availabe models
Data must have variance to compute a kernel density estimate.
AutoML steps: ['simple_algorithms', 'default_algorithms', 'ensemble']
* Step simple_algorithms will try to check up to 3 models
1_Baseline rmse 953.726855 trained in 90.3 seconds
Exception in thread QueueManagerThread:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\lolo\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Anaconda3\envs\lolo\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Anaconda3\envs\lolo\lib\site-packages\joblib\externals\loky\process_executor.py", line 615, in _queue_management_worker
    ready = wait(readers + worker_sentinels)
  File "D:\Anaconda3\envs\lolo\lib\multiprocessing\connection.py", line 879, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "D:\Anaconda3\envs\lolo\lib\multiprocessing\connection.py", line 811, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 73

**Comment by pplonski** [comment]
@bacoco thank you for reporting the issue. What Python version are you using? AutoML needs Python 3.7 or 3.8.

Did you get the error only for Baseline or for other algorithms as well? Did you train any models?

**Comment by bacoco** [comment]
Hi,
I have made test, and it's must be a windows issue. Sometimes i have the same problem with sklearn.
When i put nb_jobs=32 in AUTOML function , all work.

Thanks a lot
