### ISSUE TITLE
ufunc 'isnan' not supported for the input types

### ISSUE THREAD

**Issue by JaguarPaw2409** [mljar/mljar-supervised#333]
**Version:** 0.9.1 

**Traceback:**

1) There are no null values in the dataframe.
2) datatypes are either boolean or float.

![image](https://user-images.githubusercontent.com/10769536/110757329-4413dd80-8271-11eb-8d2b-df8b97d6e01f.png)

```python
ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
Traceback (most recent call last):
  File "miniconda3/envs/ml/lib/python3.8/site-packages/supervised/base_automl.py", line 1046, in _fit
    trained = self.train_model(params)
  File "miniconda3/envs/ml/lib/python3.8/site-packages/supervised/base_automl.py", line 354, in train_model
    mf.train(results_path, model_subpath)
  File "miniconda3/envs/ml/lib/python3.8/site-packages/supervised/model_framework.py", line 147, in train
    X_train, y_train, sample_weight = self.preprocessings[
  File "miniconda3/envs/ml/lib/python3.8/site-packages/supervised/preprocessing/preprocessing.py", line 216, in fit_and_transform
    X_train = convert.transform(X_train)
  File "miniconda3/envs/ml/lib/python3.8/site-packages/supervised/preprocessing/preprocessing_categorical.py", line 79, in transform
    X.loc[:, column] = lbl.transform(X.loc[:, column])
  File "miniconda3/envs/ml/lib/python3.8/site-packages/supervised/preprocessing/label_encoder.py", line 33, in transform
    return self.lbl.transform(x)  # list(x.values))```

**Comment by pplonski** [comment]
@JaguarPaw2409 thank you for reporting the problem. Could you please provide a data sample? Or code to create such a data sample? It will be easier to reproduce the bug.

**Comment by JaguarPaw2409** [comment]
```
supervised/preprocessing/preprocessing_categorical.py

line no 40:
PreprocessingUtils.get_type(X[column]) != PreprocessingUtils.CATEGORICAL
```

Boolean datatypes are treated as categorical variables and LabelEncoder was not working for them. I resolved the issue by converting all boolean datatypes to integers.
