### ISSUE TITLE
Import error when installed in fresh venv

### ISSUE THREAD

**Issue by daddy32** [mljar/mljar-supervised#37]
I had trouble importing the library in my current working environment, so I've created fresh venv for the test. Results were the same

Terminal output:

```bash
Successfully installed Keras-2.2.4 absl-py-0.9.0 astor-0.8.1 catboost-0.13.1 enum34-1.1.6 gast-0.3.2 grpcio-1.26.0 h5py-2.10.0 joblib-0.14.1 keras-applications-1.0.8 keras-preprocessing-1.1.0 lightgbm-2.2.3 markdown-3.1.1 mljar-supervised-0.1.7 mock-3.0.5 numpy-1.18.1 pandas-0.25.3 protobuf-3.11.2 python-dateutil-2.8.1 pytz-2019.3 pyyaml-5.3 scikit-learn-0.22.1 scipy-1.4.1 six-1.13.0 tensorboard-1.13.1 tensorflow-1.13.1 tensorflow-estimator-1.13.0 termcolor-1.1.0 tqdm-4.31.1 werkzeug-0.16.0 wheel-0.33.6 xgboost-0.80`

python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from supervised.automl import AutoML
...\automl\env\lib\site-packages\tqdm\_tqdm.py:605: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel
Traceback (most recent call last):
  File "..\automl\env\lib\site-packages\tqdm\_tqdm.py", line 613, in pandas
    from pandas.core.groupby.groupby import DataFrameGroupBy, \
ImportError: cannot import name 'DataFrameGroupBy' from 'pandas.core.groupby.groupby' (...\automl\env\lib\site-packages\pandas\core\groupby\groupby.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\automl\env\lib\site-packages\supervised\__init__.py", line 3, in <module>
    from supervised.automl import AutoML
  File "...\automl\env\lib\site-packages\supervised\automl.py", line 10, in <module>
    tqdm.pandas()
  File "...\automl\env\lib\site-packages\tqdm\_tqdm.py", line 616, in pandas
    from pandas.core.groupby import DataFrameGroupBy, \
ImportError: cannot import name 'PanelGroupBy' from 'pandas.core.groupby' (C:\PKZ\Synced_dirs\Devel\Python\automl\env\lib\site-packages\pandas\core\groupby\__init__.py)
...
```

As per tqdm issue log, this seems to be fixed in newer version of this library, however pip installation of mljar-supervised installs the pre-fix release.

**Comment by pplonski** [comment]
Hey! Are you able to fix it for yourself or do you need help? Please take a look at https://github.com/mljar/mljar-supervised/pull/30/commits/0ac46a09c9294152ee63153b85f43b31fc00a897 Right now, I'm working on new UI version for mljar (plan is to open source it), after that I've planned to switch to polish this package.

**Comment by daddy32** [comment]
No help needed, thanks. I just didn't see the PR or similar issue, so I've reported the problem for your benefit.

**Comment by pplonski** [comment]
Should be fixed.
