### ISSUE TITLE
problem with pandas library 

### ISSUE THREAD

**Issue by Tharunkumar01** [mljar/mljar-supervised#392]
Below is the error message I get
`## Error for 1_DecisionTree

cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 1074, in _fit
    trained = self.train_model(params)
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 360, in train_model
    mf.save(results_path, model_subpath)
  File "/opt/conda/lib/python3.7/site-packages/supervised/model_framework.py", line 444, in save
    predictions.to_csv(self._oof_predictions_fname, index=False)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 3145, in to_csv
    >>> df = pd.DataFrame(dict(name=['Raphael', 'Donatello'],
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 12, in <module>
    from pandas._typing import (
ImportError: cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)

Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

## Error for 1_DecisionTree

cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 1074, in _fit
    trained = self.train_model(params)
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 360, in train_model
    mf.save(results_path, model_subpath)
  File "/opt/conda/lib/python3.7/site-packages/supervised/model_framework.py", line 444, in save
    predictions.to_csv(self._oof_predictions_fname, index=False)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 3145, in to_csv
    >>> df = pd.DataFrame(dict(name=['Raphael', 'Donatello'],
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 12, in <module>
    from pandas._typing import (
ImportError: cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)

Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

## Error for 2_DecisionTree

cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 1074, in _fit
    trained = self.train_model(params)
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 360, in train_model
    mf.save(results_path, model_subpath)
  File "/opt/conda/lib/python3.7/site-packages/supervised/model_framework.py", line 444, in save
    predictions.to_csv(self._oof_predictions_fname, index=False)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 3145, in to_csv
    >>> df = pd.DataFrame(dict(name=['Raphael', 'Donatello'],
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 12, in <module>
    from pandas._typing import (
ImportError: cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)

Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

## Error for 3_DecisionTree

cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 1074, in _fit
    trained = self.train_model(params)
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 360, in train_model
    mf.save(results_path, model_subpath)
  File "/opt/conda/lib/python3.7/site-packages/supervised/model_framework.py", line 444, in save
    predictions.to_csv(self._oof_predictions_fname, index=False)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 3145, in to_csv
    >>> df = pd.DataFrame(dict(name=['Raphael', 'Donatello'],
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 12, in <module>
    from pandas._typing import (
ImportError: cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)

Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

## Error for 1_Default_LightGBM

cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 1074, in _fit
    trained = self.train_model(params)
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 357, in train_model
    mf.train(results_path, model_subpath)
  File "/opt/conda/lib/python3.7/site-packages/supervised/model_framework.py", line 230, in train
    self._max_time_for_learner,
  File "/opt/conda/lib/python3.7/site-packages/supervised/algorithms/lightgbm.py", line 251, in fit
    result.to_csv(log_to_file, index=False, header=False)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 3145, in to_csv
    >>> df = pd.DataFrame(dict(name=['Raphael', 'Donatello'],
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 12, in <module>
    from pandas._typing import (
ImportError: cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)

Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

## Error for 2_Default_CatBoost

cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 1074, in _fit
    trained = self.train_model(params)
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 357, in train_model
    mf.train(results_path, model_subpath)
  File "/opt/conda/lib/python3.7/site-packages/supervised/model_framework.py", line 230, in train
    self._max_time_for_learner,
  File "/opt/conda/lib/python3.7/site-packages/supervised/algorithms/catboost.py", line 263, in fit
    result.to_csv(log_to_file, index=False, header=False)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 3145, in to_csv
    >>> df = pd.DataFrame(dict(name=['Raphael', 'Donatello'],
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 12, in <module>
    from pandas._typing import (
ImportError: cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)

Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

## Error for 3_Default_RandomForest

cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 1074, in _fit
    trained = self.train_model(params)
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 357, in train_model
    mf.train(results_path, model_subpath)
  File "/opt/conda/lib/python3.7/site-packages/supervised/model_framework.py", line 230, in train
    self._max_time_for_learner,
  File "/opt/conda/lib/python3.7/site-packages/supervised/algorithms/sklearn.py", line 171, in fit
    df_result.to_csv(log_to_file, index=False, header=False)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 3145, in to_csv
    >>> df = pd.DataFrame(dict(name=['Raphael', 'Donatello'],
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 12, in <module>
    from pandas._typing import (
ImportError: cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)

Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

## Error for 4_Default_ExtraTrees

cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 1074, in _fit
    trained = self.train_model(params)
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 357, in train_model
    mf.train(results_path, model_subpath)
  File "/opt/conda/lib/python3.7/site-packages/supervised/model_framework.py", line 230, in train
    self._max_time_for_learner,
  File "/opt/conda/lib/python3.7/site-packages/supervised/algorithms/sklearn.py", line 171, in fit
    df_result.to_csv(log_to_file, index=False, header=False)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 3145, in to_csv
    >>> df = pd.DataFrame(dict(name=['Raphael', 'Donatello'],
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 12, in <module>
    from pandas._typing import (
ImportError: cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)

Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

## Error for 1_LightGBM

cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 1074, in _fit
    trained = self.train_model(params)
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 357, in train_model
    mf.train(results_path, model_subpath)
  File "/opt/conda/lib/python3.7/site-packages/supervised/model_framework.py", line 230, in train
    self._max_time_for_learner,
  File "/opt/conda/lib/python3.7/site-packages/supervised/algorithms/lightgbm.py", line 251, in fit
    result.to_csv(log_to_file, index=False, header=False)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 3145, in to_csv
    >>> df = pd.DataFrame(dict(name=['Raphael', 'Donatello'],
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 12, in <module>
    from pandas._typing import (
ImportError: cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)

Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

## Error for 10_CatBoost

cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 1074, in _fit
    trained = self.train_model(params)
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 357, in train_model
    mf.train(results_path, model_subpath)
  File "/opt/conda/lib/python3.7/site-packages/supervised/model_framework.py", line 230, in train
    self._max_time_for_learner,
  File "/opt/conda/lib/python3.7/site-packages/supervised/algorithms/catboost.py", line 263, in fit
    result.to_csv(log_to_file, index=False, header=False)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 3145, in to_csv
    >>> df = pd.DataFrame(dict(name=['Raphael', 'Donatello'],
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 12, in <module>
    from pandas._typing import (
ImportError: cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)

Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

## Error for 19_RandomForest

cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 1074, in _fit
    trained = self.train_model(params)
  File "/opt/conda/lib/python3.7/site-packages/supervised/base_automl.py", line 357, in train_model
    mf.train(results_path, model_subpath)
  File "/opt/conda/lib/python3.7/site-packages/supervised/model_framework.py", line 230, in train
    self._max_time_for_learner,
  File "/opt/conda/lib/python3.7/site-packages/supervised/algorithms/sklearn.py", line 171, in fit
    df_result.to_csv(log_to_file, index=False, header=False)
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py", line 3145, in to_csv
    >>> df = pd.DataFrame(dict(name=['Raphael', 'Donatello'],
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 12, in <module>
    from pandas._typing import (
ImportError: cannot import name 'CompressionOptions' from 'pandas._typing' (/opt/conda/lib/python3.7/site-packages/pandas/_typing.py)

Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

 Save`

**Comment by pplonski** [comment]
@Tharunkumar01 thanks for reporting. Could you please send a data example and code so I can reproduce the issue?

**Comment by pplonski** [comment]
@Tharunkumar01 I'm closing the issue. Please provide more information how to reproduce the problem and reopen the issue.
