### ISSUE TITLE
'float' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Lssousadc** [mljar/mljar-supervised#457]
**'float' object has no attribute 'lower'**

Traceback (most recent call last):
  File "C:\Users\lucas.ssousa\AppData\Roaming\Python\Python38\site-packages\supervised\base_automl.py", line 1078, in _fit
    trained = self.train_model(params)
  File "C:\Users\lucas.ssousa\AppData\Roaming\Python\Python38\site-packages\supervised\base_automl.py", line 365, in train_model
    mf.train(results_path, model_subpath)
  File "C:\Users\lucas.ssousa\AppData\Roaming\Python\Python38\site-packages\supervised\model_framework.py", line 184, in train
    X_train, y_train, sample_weight = self.preprocessings[
  File "C:\Users\lucas.ssousa\AppData\Roaming\Python\Python38\site-packages\supervised\preprocessing\preprocessing.py", line 165, in fit_and_transform
    t.fit(X_train, col)
  File "C:\Users\lucas.ssousa\AppData\Roaming\Python\Python38\site-packages\supervised\preprocessing\text_transformer.py", line 25, in fit
    self._vectorizer.fit(x)
  File "C:\Users\lucas.ssousa\AppData\Roaming\Python\Python38\site-packages\sklearn\feature_extraction\text.py", line 1823, in fit
    X = super().fit_transform(raw_documents)
  File "C:\Users\lucas.ssousa\AppData\Roaming\Python\Python38\site-packages\sklearn\feature_extraction\text.py", line 1202, in fit_transform
    vocabulary, X = self._count_vocab(raw_documents,
  File "C:\Users\lucas.ssousa\AppData\Roaming\Python\Python38\site-packages\sklearn\feature_extraction\text.py", line 1114, in _count_vocab
    for feature in analyze(doc):
  File "C:\Users\lucas.ssousa\AppData\Roaming\Python\Python38\site-packages\sklearn\feature_extraction\text.py", line 104, in _analyze
    doc = preprocessor(doc)
  File "C:\Users\lucas.ssousa\AppData\Roaming\Python\Python38\site-packages\sklearn\feature_extraction\text.py", line 69, in _preprocess
    doc = doc.lower()
AttributeError: 'float' object has no attribute 'lower'

Can anyone help me with this error? I have tried to work with other kind of models and my data worked normal. But when I try using MLJAR AutoML, it shows me this error.

**Comment by pplonski** [comment]
@Lssousadc can you share the code and data that can be used to reproduce the error?

**Comment by pplonski** [comment]
@Lssousadc I'm closing the issue, I can't reproduce it without example data and code.
