### ISSUE TITLE
'TfidfVectorizer' object has no attribute 'get_feature_names_out'

### ISSUE THREAD

**Issue by leahmcguire** [mljar/mljar-supervised#494]
'TfidfVectorizer' object has no attribute 'get_feature_names_out'
Traceback (most recent call last):
  File "/Users/lmcguire/.pyenv/versions/3.8.11/envs/machine-learning/lib/python3.8/site-packages/supervised/base_automl.py", line 1084, in _fit
    trained = self.train_model(params)
  File "/Users/lmcguire/.pyenv/versions/3.8.11/envs/machine-learning/lib/python3.8/site-packages/supervised/base_automl.py", line 371, in train_model
    mf.train(results_path, model_subpath)
  File "/Users/lmcguire/.pyenv/versions/3.8.11/envs/machine-learning/lib/python3.8/site-packages/supervised/model_framework.py", line 184, in train
    X_train, y_train, sample_weight = self.preprocessings[
  File "/Users/lmcguire/.pyenv/versions/3.8.11/envs/machine-learning/lib/python3.8/site-packages/supervised/preprocessing/preprocessing.py", line 165, in fit_and_transform
    t.fit(X_train, col)
  File "/Users/lmcguire/.pyenv/versions/3.8.11/envs/machine-learning/lib/python3.8/site-packages/supervised/preprocessing/text_transformer.py", line 27, in fit
    for f in list(self._vectorizer.get_feature_names_out()):
AttributeError: 'TfidfVectorizer' object has no attribute 'get_feature_names_out'

**Comment by pplonski** [comment]
Thank you for reporting. Could you please provide minimal example to reproduce the issue?

**Comment by leahmcguire** [comment]
I cannot share the data that produced this error - however I suspect that any set of features that triggers the use of the TfidfVectorizer will produce this error.

**Comment by pplonski** [comment]
@leahmcguire what version of sklearn are you using? Can you try to upgrade sklearn version:

```
pip install -U scikit-learn
```

**Comment by jkozuchowska** [comment]
Hi,
I've encountered the same problem while trying to run the Titanic example (using the data provided in tests/data/Titanic directory and code given in examples/notebooks/Titanic.ipynb). 
I'm using sklearn version 0.24.2.

**Comment by pplonski** [comment]
@jkozuchowska can you upgrade the sklearn? with `pip install -U scikit-learn`

**Comment by pplonski** [comment]
@MaciekEO we should update the `scikit-learn` minimum version in `requirements.txt`.

**Comment by sayalijadhao19** [comment]
> @leahmcguire what version of sklearn are you using? Can you try to upgrade sklearn version:
> 
> ```
> pip install -U scikit-learn
> ```

THIS WORKS!
