### ISSUE TITLE
Binary classification: not all labels in one fold

### ISSUE THREAD

**Issue by adalli13** [mljar/mljar-supervised#532]
Hello,
I've got a binary classification problem whereby the labels are unequally distributed in my data so that there may be some folds which only include one label. This leads to the following error:

```
y_true contains only one label (0). Please provide the true labels explicitly through the labels argument.
Traceback (most recent call last):
  File "[...]\Python\Python38\site-packages\supervised\base_automl.py", line 1087, in _fit
    trained = self.train_model(params)
  File "[...]\Python\Python38\site-packages\supervised\base_automl.py", line 372, in train_model
    mf.train(results_path, model_subpath)
  File "[...]\Python\Python38\site-packages\supervised\model_framework.py", line 233, in train
    learner.fit(
  File "[...]\Python\Python38\site-packages\supervised\algorithms\sklearn.py", line 140, in fit
    tr = self.log_metric(
  File "[...]\Python\Python38\site-packages\supervised\utils\metric.py", line 408, in __call__
    return self.metric(y_true, y_predicted, sample_weight=sample_weight)
  File "[...]\Python\Python38\site-packages\supervised\utils\metric.py", line 25, in logloss
    ll = log_loss(y_true, y_predicted, sample_weight=sample_weight)
  File "[...]\lib\site-packages\sklearn\metrics\_classification.py", line 2391, in log_loss
    raise ValueError(
ValueError: y_true contains only one label (0). Please provide the true labels explicitly through the labels argument.
```

Edit: shuffling the dataframe before handing it over to the .fit() function helps at least in my case

**Comment by pplonski** [comment]
I will need code and data to reproduce the issue. But I can't tell when it will be fixed. I'm focused right now on another [project](https://github.com/mljar/mercury).

**Comment by adalli13** [comment]
Unfortunately, I did not manage to create any "artificial" data which lead to the same error.
