### ISSUE TITLE
Xgboost_categorical_mix: TypeError: ufunc 'isnan' not supported 

### ISSUE THREAD

**Issue by PeteKinz** [mljar/mljar-supervised#547]
Hello everyone

I trained several models and I can use all of them to make predictions, except those models which use an "Xgboost_categorical_mix" in the Ensemlbe model.

After running `model.predict(data)` I get this error:
`
Traceback (most recent call last):
  File "/Users/thiloreintjes/Desktop/Bachelorarbeit/GitLab/Pipeline/pipeline_main.py", line 371, in <module>
    print(pred_with_models(per_class_models, test_df))
  File "/Users/thiloreintjes/Desktop/Bachelorarbeit/GitLab/Pipeline/pipeline_main.py", line 326, in pred_with_models
    pred = models[model].predict(data_to_pred)
  File "/Users/thiloreintjes/Desktop/Bachelorarbeit/GitLab/venv/lib/python3.7/site-packages/supervised/automl.py", line 387, in predict
    return self._predict(X)
  File "/Users/thiloreintjes/Desktop/Bachelorarbeit/GitLab/venv/lib/python3.7/site-packages/supervised/base_automl.py", line 1361, in _predict
    predictions = self._base_predict(X)
  File "/Users/thiloreintjes/Desktop/Bachelorarbeit/GitLab/venv/lib/python3.7/site-packages/supervised/base_automl.py", line 1318, in _base_predict
    X_stacked = self.get_stacked_data(X, mode="predict")
  File "/Users/thiloreintjes/Desktop/Bachelorarbeit/GitLab/venv/lib/python3.7/site-packages/supervised/base_automl.py", line 421, in get_stacked_data
    oof = m.predict(X)
  File "/Users/thiloreintjes/Desktop/Bachelorarbeit/GitLab/venv/lib/python3.7/site-packages/supervised/ensemble.py", line 308, in predict
    y_predicted_from_model = model.predict(X)
  File "/Users/thiloreintjes/Desktop/Bachelorarbeit/GitLab/venv/lib/python3.7/site-packages/supervised/model_framework.py", line 428, in predict
    X_data, _, _ = self.preprocessings[ind].transform(X.copy(), None)
  File "/Users/thiloreintjes/Desktop/Bachelorarbeit/GitLab/venv/lib/python3.7/site-packages/supervised/preprocessing/preprocessing.py", line 403, in transform
    X_validation = convert.transform(X_validation)
  File "/Users/thiloreintjes/Desktop/Bachelorarbeit/GitLab/venv/lib/python3.7/site-packages/supervised/preprocessing/preprocessing_categorical.py", line 79, in transform
    X.loc[:, column] = lbl.transform(X.loc[:, column])
  File "/Users/thiloreintjes/Desktop/Bachelorarbeit/GitLab/venv/lib/python3.7/site-packages/supervised/preprocessing/label_encoder.py", line 33, in transform
    return self.lbl.transform(x)  # list(x.values))
  File "/Users/thiloreintjes/Desktop/Bachelorarbeit/GitLab/venv/lib/python3.7/site-packages/sklearn/preprocessing/_label.py", line 138, in transform
    return _encode(y, uniques=self.classes_)
  File "/Users/thiloreintjes/Desktop/Bachelorarbeit/GitLab/venv/lib/python3.7/site-packages/sklearn/utils/_encode.py", line 187, in _encode
    diff = _check_unknown(values, uniques)
  File "/Users/thiloreintjes/Desktop/Bachelorarbeit/GitLab/venv/lib/python3.7/site-packages/sklearn/utils/_encode.py", line 261, in _check_unknown
    if np.isnan(known_values).any():
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
`

The column that is causing this containes float values, looking like this: [-0.12732930600575765, -0.12732930600575765, 0.12732930600575765]
When the data reaches the `_check_unknown` method, all floats are converted to strings

I don't know how to deal with this, other than to not use models which use Xgboost_categorical_mix...

**Comment by pplonski** [comment]
@PeteKinz thanks for reporting the issue. You can set `mix_encoding=False` in the `AutoML()` constructor to disable the mixed categoricals approach.

Are you sure you don't have some strange values in the data in those columns? Maybe some missing values are marked in a different way than in training data? There must be something changed in the data ... Sorry that it is not handled properly.

**Comment by PeteKinz** [comment]
Thanks for the fast response!
I double checked with the `convert_params` in the framework.json file and the values do match.
The data I am using to predinct should be fine. I checked each value, since I'm only trying to predict 3 samples
Nevertheless, thank you for the workaround!
