### ISSUE TITLE
Unable to load model on Ubuntu

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [mljar/mljar-supervised#561]
I'm successfully training and loading models on Windows, but when I try to run/save/load the exact same code on Ubuntu I get this error:

```
model = AutoML(results_path="AutoML")
model.predict(features)
```
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/base_automl.py", line 203, in load
    m = ModelFramework.load(path, model_subpath, lazy_load)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/model_framework.py", line 591, in load
    l = AlgorithmFactory.load(learner_desc, learner_path, lazy_load)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/algorithms/factory.py", line 27, in load
    learner.reload()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/algorithms/algorithm.py", line 36, in reload
    self.load(self.model_file_path)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/algorithms/sklearn.py", line 50, in load
    self.model = joblib.load(model_file_path)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 579, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'AutoML/1_DecisionTree\\learner_fold_0.decision_tree'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/automl.py", line 387, in predict
    return self._predict(X)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/base_automl.py", line 1361, in _predict
    predictions = self._base_predict(X)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/base_automl.py", line 1293, in _base_predict
    self.load(self.results_path)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/base_automl.py", line 226, in load
    raise AutoMLException(f"Cannot load AutoML directory. {str(e)}")
supervised.exceptions.AutoMLException: Cannot load AutoML directory. [Errno 2] No such file or directory: 'AutoML/1_DecisionTree\\learner_fold_0.decision_tree'
```
Similar issue happens when trying to load the model via pickle or joblib.

```
model = pd.read_pickle('mastermind/AI/mljar/automl_regression.pkl')
model.predict(features)
```
```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/automl.py", line 387, in predict
    return self._predict(X)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/base_automl.py", line 1361, in _predict
    predictions = self._base_predict(X)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/base_automl.py", line 1318, in _base_predict
    X_stacked = self.get_stacked_data(X, mode="predict")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/base_automl.py", line 421, in get_stacked_data
    oof = m.predict(X)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/ensemble.py", line 308, in predict
    y_predicted_from_model = model.predict(X)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/model_framework.py", line 429, in predict
    y_p = learner.predict(X_data)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/algorithms/lightgbm.py", line 270, in predict
    self.reload()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/algorithms/algorithm.py", line 36, in reload
    self.load(self.model_file_path)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/supervised/algorithms/lightgbm.py", line 285, in load
    self.model = lgb.Booster(model_file=model_file_path)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/lightgbm/basic.py", line 2639, in __init__
    _safe_call(_LIB.LGBM_BoosterCreateFromModelfile(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/lightgbm/basic.py", line 125, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
lightgbm.basic.LightGBMError: Could not open AutoML/37_LightGBM/learner_fold_0.lightgbm
```

**Comment by Karlheinzniebuhr** [comment]
Solved. It was my own local path mistake
