### ISSUE TITLE
float64 column treated as text in `feature_extraction/text.py`

### ISSUE THREAD

**Issue by jonashaag** [mljar/mljar-supervised#576]
```
Traceback (most recent call last):
  File "/opt/conda/envs/X/lib/python4.10/site-packages/supervised/base_automl.py", line 1088, in _fit
    trained = self.train_model(params)
  File "/opt/conda/envs/X/lib/python3.10/site-packages/supervised/base_automl.py", line 372, in train_model
    mf.train(results_path, model_subpath)
  File "/opt/conda/envs/X/lib/python3.10/site-packages/supervised/model_framework.py", line 186, in train
    ].fit_and_transform(
  File "/opt/conda/envs/X/lib/python3.10/site-packages/supervised/preprocessing/preprocessing.py", line 165, in fit_and_transform
    t.fit(X_train, col)
  File "/opt/conda/envs/X/lib/python3.10/site-packages/supervised/preprocessing/text_transformer.py", line 26, in fit
    self._vectorizer.fit(x)
  File "/opt/conda/envs/X/lib/python3.10/site-packages/sklearn/feature_extraction/text.py", line 2048, in fit
    X = super().fit_transform(raw_documents)
  File "/opt/conda/envs/X/lib/python3.10/site-packages/sklearn/feature_extraction/text.py", line 1338, in fit_transform
    vocabulary, X = self._count_vocab(raw_documents, self.fixed_vocabulary_)
  File "/opt/conda/envs/X/lib/python3.10/site-packages/sklearn/feature_extraction/text.py", line 1209, in _count_vocab
    for feature in analyze(doc):
  File "/opt/conda/envs/X/lib/python3.10/site-packages/sklearn/feature_extraction/text.py", line 111, in _analyze
    doc = preprocessor(doc)
  File "/opt/conda/envs/X/lib/python3.10/site-packages/sklearn/feature_extraction/text.py", line 69, in _preprocess
    doc = doc.lower()
AttributeError: 'numpy.float64' object has no attribute 'lower'
```

**Comment by pplonski** [comment]
Hi @jonashaag, thank you for reporting the issue. Could you please run the `np.unique()` on the column that is causing the error?

**Comment by jonashaag** [comment]
I will try, best debugging I can do is a print statement but it doesn't seem like it's printed somewhere. I'll keep on trying.

I've commented out text preprocessing and now get another preprocessing error:

```
ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
Traceback (most recent call last):
  File "/opt/conda/envs/X/lib/python3.10/site-packages/supervised/base_automl.py", line 1088, in _fit
    trained = self.train_model(params)
  File "/opt/conda/envs/X/lib/python3.10/site-packages/supervised/base_automl.py", line 372, in train_model
    mf.train(results_path, model_subpath)
  File "/opt/conda/envs/X/lib/python3.10/site-packages/supervised/model_framework.py", line 186, in train
    ].fit_and_transform(
  File "/opt/conda/envs/X/lib/python3.10/site-packages/supervised/preprocessing/preprocessing.py", line 222, in fit_and_transform
    X_train = convert.transform(X_train)
  File "/opt/conda/envs/X/lib/python3.10/site-packages/supervised/preprocessing/preprocessing_categorical.py", line 79, in transform
    X.loc[:, column] = lbl.transform(X.loc[:, column])
  File "/opt/conda/envs/X/lib/python3.10/site-packages/supervised/preprocessing/label_encoder.py", line 33, in transform
    return self.lbl.transform(x)  # list(x.values))
  File "/opt/conda/envs/X/lib/python3.10/site-packages/sklearn/preprocessing/_label.py", line 138, in transform
    return _encode(y, uniques=self.classes_)
  File "/opt/conda/envs/X/lib/python3.10/site-packages/sklearn/utils/_encode.py", line 229, in _encode
    diff = _check_unknown(values, uniques)
  File "/opt/conda/envs/X/lib/python3.10/site-packages/sklearn/utils/_encode.py", line 303, in _check_unknown
    if np.isnan(known_values).any():
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by jonashaag** [comment]
Seems like to columns are sparse float64. Feel free to close since supervised doesn't seem to have sparse support just yet.
