### ISSUE TITLE
Error for Ensemble

### ISSUE THREAD

**Issue by junyuyang7** [mljar/mljar-supervised#621]
## Error for Ensemble

Input contains NaN, infinity or a value too large for dtype('float64').
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\supervised\base_automl.py", line 1084, in _fit
    is_stacked=params["is_stacked"]
  File "d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\supervised\base_automl.py", line 401, in ensemble_step
    self.ensemble.fit(oofs, target, sample_weight)
  File "d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\supervised\ensemble.py", line 236, in fit
    score = self.metric(y, y_ens, sample_weight)
  File "d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\supervised\utils\metric.py", line 408, in __call__
    return self.metric(y_true, y_predicted, sample_weight=sample_weight)
  File "d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\supervised\utils\metric.py", line 25, in logloss
    ll = log_loss(y_true, y_predicted, sample_weight=sample_weight)
  File "d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_classification.py", line 2379, in log_loss
    y_pred = check_array(y_pred, ensure_2d=False)
  File "d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\sklearn\utils\validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\sklearn\utils\validation.py", line 116, in _assert_all_finite
    type_err, msg_dtype if msg_dtype is not None else X.dtype
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

How can I do to deal with it？

**Comment by pplonski** [comment]
Thank you @junyuyang7 for reporting the issue. Is it possible to provide data and code to reproduce the issue? This might be some bug in the code. Thanks!
