### ISSUE TITLE
Problem about param ml_task="regression",

### ISSUE THREAD

**Issue by jiaqizheng2000** [mljar/mljar-supervised#643]
If I use this param, it will raise an issue below for all of the model, if it is deleted, the model works fine.

'<' not supported between instances of 'numpy.ndarray' and 'str'
Traceback (most recent call last):
  File "C:\Users\ZHENGJ\AppData\Local\Programs\Python\Python39\lib\site-packages\supervised\base_automl.py", line 1195, in _fit
    trained = self.train_model(params)
  File "C:\Users\ZHENGJ\AppData\Local\Programs\Python\Python39\lib\site-packages\supervised\base_automl.py", line 404, in train_model
    self.keep_model(mf, model_subpath)
  File "C:\Users\ZHENGJ\AppData\Local\Programs\Python\Python39\lib\site-packages\supervised\base_automl.py", line 317, in keep_model
    self.select_and_save_best()
  File "C:\Users\ZHENGJ\AppData\Local\Programs\Python\Python39\lib\site-packages\supervised\base_automl.py", line 1315, in select_and_save_best
    self._best_model = min(
TypeError: '<' not supported between instances of 'numpy.ndarray' and 'str'

**Comment by Benjamin-Frost** [comment]
Same issue here. Did you manage to resolve it?

**Comment by pplonski** [comment]
Hi @jiaqizheng2000, @Benjamin-Frost,
Could you please provide code to reproduce the issue? Thank you!

**Comment by jiaqizheng2000** [comment]
automl = AutoML(
                    ml_task="regression",
                    train_ensemble=True,
                    fairness_threshold=0.8,
                    results_path=resultpath,
                    model_time_limit=30 * 60,
                    start_random_models=10,
                    top_models_to_improve=3,
                    hill_climbing_steps=3,
                    golden_features=True,
                    features_selection=False,
                    stack_models=True,
                    explain_level=2,
                    validation_strategy={
                        "validation_type": "kfold",
                        "k_folds": 4,
                        "shuffle": False,
                        "stratify": True,}
         )
    automl.fit(x_train, y_train)

**Comment by pplonski** [comment]
Could you please share dataset as well? or maybe data sample, do you have this error on synthetic data as well?

**Comment by jiaqizheng2000** [comment]
[example.xlsx](https://github.com/mljar/mljar-supervised/files/13870946/example.xlsx)

**Comment by pplonski** [comment]
Thank you! How do you load code and prepare `X_train` and `y_train` variables?

**Comment by jiaqizheng2000** [comment]
Simply choose the first column as y_train, and the rest as X_train

**Comment by pplonski** [comment]
Sure @Rohan581, thanks!

**Comment by harshvkpandey** [comment]
@pplonsk can I work on this, as it hasn't been resolved yet?

**Comment by pplonski** [comment]
Sure @harshvkpandey it is yours! Thx 👍

**Comment by jayyycodes** [comment]
Hi, is this still being worked on? Happy to pick it up if not.

**Comment by pplonski** [comment]
Thanks @jayyycodes for looking into this, can you reproduce the issue?

**Comment by jayyycodes** [comment]
Not yet, I'll set it up and try reproducing it now — will update here once I have results.
