### ISSUE TITLE
custom eval function

### ISSUE THREAD

**Issue by bardamchop** [mljar/mljar-supervised#685]
I'm trying to write a function to use a custom logloss function for multi class problem and I am getting the following error. I don't get this error when I run the same thing 

np.random.seed(42)  # for reproducibility
y_true = np.random.randint(0, 3, size=(1000,))
y_pred = np.random.rand(1000, 3)
y_pred /= y_pred.sum(axis=1, keepdims=True)  # normalize to probabilities

#y_true = np.full(100, 2)
#y_pred = np.zeros((100, 3))
#y_pred[:, 1] = 1.0

misclassification_weight = 2.0
loss = custom_log_loss(y_true, y_pred, misclassification_weight)
This works in my local environment but using mljar I am getting the following
I don't see the problem with this line
custom_loss = -np.mean(np.log(y_pred_prob[indices, y_true] + epsilon) * penalty)

Error for 1_Default_LightGBM
arrays used as indices must be of integer (or boolean) type Traceback (most recent call last): File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/base_automl.py", line 1195, in _fit trained = self.train_model(params) File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/base_automl.py", line 401, in train_model mf.train(results_path, model_subpath) File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/model_framework.py", line 254, in train learner.fit( File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/algorithms/lightgbm.py", line 237, in fit self.model = lgb.train( File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/lightgbm/engine.py", line 282, in train evaluation_result_list.extend(booster.eval_train(feval)) File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/lightgbm/basic.py", line 3892, in eval_train return self.__inner_eval(self._train_data_name, 0, feval) File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/lightgbm/basic.py", line 4635, in __inner_eval feval_ret = eval_function(self.__inner_predict(data_idx), cur_data) File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/utils/metric.py", line 335, in lightgbm_eval_metric_user_defined return "user_defined_metric", metric(target, preds, sample_weight=weight), False File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/utils/metric.py", line 319, in call return UserDefinedEvalMetric.eval_metric(y_true, y_predicted, sample_weight) File "/tmp/ipykernel_4857/3455554431.py", line 33, in custom_scoring_function custom_loss = -np.mean(np.log(y_pred_prob[indices, y_true] + epsilon) * penalty) IndexError: arrays used as indices must be of integer (or boolean) type

Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

Error for 1_LightGBM
arrays used as indices must be of integer (or boolean) type Traceback (most recent call last): File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/base_automl.py", line 1195, in _fit trained = self.train_model(params) File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/base_automl.py", line 401, in train_model mf.train(results_path, model_subpath) File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/model_framework.py", line 254, in train learner.fit( File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/algorithms/lightgbm.py", line 237, in fit self.model = lgb.train( File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/lightgbm/engine.py", line 282, in train evaluation_result_list.extend(booster.eval_train(feval)) File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/lightgbm/basic.py", line 3892, in eval_train return self.__inner_eval(self._train_data_name, 0, feval) File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/lightgbm/basic.py", line 4635, in __inner_eval feval_ret = eval_function(self.__inner_predict(data_idx), cur_data) File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/utils/metric.py", line 335, in lightgbm_eval_metric_user_defined return "user_defined_metric", metric(target, preds, sample_weight=weight), False File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/utils/metric.py", line 319, in call return UserDefinedEvalMetric.eval_metric(y_true, y_predicted, sample_weight) File "/tmp/ipykernel_4857/3455554431.py", line 33, in custom_scoring_function custom_loss = -np.mean(np.log(y_pred_prob[indices, y_true] + epsilon) * penalty) IndexError: arrays used as indices must be of integer (or boolean) type

Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

Error for 2_LightGBM
arrays used as indices must be of integer (or boolean) type Traceback (most recent call last): File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/base_automl.py", line 1195, in _fit trained = self.train_model(params) File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/base_automl.py", line 401, in train_model mf.train(results_path, model_subpath) File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/model_framework.py", line 254, in train learner.fit( File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/algorithms/lightgbm.py", line 237, in fit self.model = lgb.train( File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/lightgbm/engine.py", line 282, in train evaluation_result_list.extend(booster.eval_train(feval)) File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/lightgbm/basic.py", line 3892, in eval_train return self.__inner_eval(self._train_data_name, 0, feval) File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/lightgbm/basic.py", line 4635, in __inner_eval feval_ret = eval_function(self.__inner_predict(data_idx), cur_data) File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/utils/metric.py", line 335, in lightgbm_eval_metric_user_defined return "user_defined_metric", metric(target, preds, sample_weight=weight), False File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/supervised/utils/metric.py", line 319, in call return UserDefinedEvalMetric.eval_metric(y_true, y_predicted, sample_weight) File "/tmp/ipykernel_4857/3455554431.py", line 33, in custom_scoring_function custom_loss = -np.mean(np.log(y_pred_prob[indices, y_true] + epsilon) * penalty) IndexError: arrays used as indices must be of integer (or boolean) type

Please set a GitHub issue with above error message at: https://github.com/mljar/mljar-supervised/issues/new

**Comment by bardamchop** [comment]
This has to do with my numpy versions. Closing the issue
