### ISSUE TITLE
Error for 4_Default_Xgboost

### ISSUE THREAD

**Issue by carlos-zager-toteat** [mljar/mljar-supervised#686]
ufunc 'less' did not contain a loop with signature matching types (<class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.StrDType'>) -> None
Traceback (most recent call last):
  File "/Users/carlos/virtenvs/ai/lib/python3.10/site-packages/supervised/base_automl.py", line 1195, in _fit
    trained = self.train_model(params)
  File "/Users/carlos/virtenvs/ai/lib/python3.10/site-packages/supervised/base_automl.py", line 404, in train_model
    self.keep_model(mf, model_subpath)
  File "/Users/carlos/virtenvs/ai/lib/python3.10/site-packages/supervised/base_automl.py", line 317, in keep_model
    self.select_and_save_best()
  File "/Users/carlos/virtenvs/ai/lib/python3.10/site-packages/supervised/base_automl.py", line 1313, in select_and_save_best
    self._best_model = min(
numpy.core._exceptions._UFuncNoLoopError: ufunc 'less' did not contain a loop with signature matching types (<class 'numpy.dtypes.Float64DType'>, <class 'numpy.dtypes.StrDType'>) -> None

**Comment by pplonski** [comment]
Hi @carlos-zager-toteat,

Thank you for reporting the issue. Could you please provide code and data to reproduce the issue?
