### ISSUE TITLE
error in docker installation

### ISSUE THREAD

**Issue by pplonski** [mljar/mljar-supervised#739]
```
 > [15/25] RUN pip install mljar-supervised:                                                             
#0 0.914 Collecting mljar-supervised                                                                     
#0 0.926   Downloading mljar-supervised-1.1.9.tar.gz (127 kB)                                            
#0 0.974   Preparing metadata (setup.py): started                                                        
#0 1.285   Preparing metadata (setup.py): finished with status 'done'                                    
#0 1.294 Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.8/dist-packages (from mljar-supervised) (1.24.4)
#0 1.296 Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from mljar-supervised) (2.0.3)
#0 1.542 Collecting scipy<=1.11.4,>=1.6.1 (from mljar-supervised)
#0 1.546   Downloading scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (58 kB)
#0 1.785 Collecting scikit-learn>=1.0 (from mljar-supervised)
#0 1.793   Downloading scikit_learn-1.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
#0 1.855 Collecting xgboost>=2.0.0 (from mljar-supervised)
#0 1.860   Downloading xgboost-2.1.0-py3-none-manylinux_2_28_x86_64.whl.metadata (2.1 kB)
#0 1.905 Collecting lightgbm>=3.0.0 (from mljar-supervised)
#0 1.910   Downloading lightgbm-4.5.0-py3-none-manylinux_2_28_x86_64.whl.metadata (17 kB)
#0 2.051 Collecting catboost>=0.24.4 (from mljar-supervised)
#0 2.056   Downloading catboost-1.2.5-cp38-cp38-manylinux2014_x86_64.whl.metadata (1.2 kB)
#0 2.097 Collecting joblib>=1.0.1 (from mljar-supervised)
#0 2.102   Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
#0 2.128 Collecting tabulate>=0.8.7 (from mljar-supervised)
#0 2.133   Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
#0 2.336 Collecting matplotlib>=3.2.2 (from mljar-supervised)
#0 2.340   Downloading matplotlib-3.7.5-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (5.7 kB)
#0 2.384 Collecting dtreeviz>=2.2.2 (from mljar-supervised)
#0 2.389   Downloading dtreeviz-2.2.2-py3-none-any.whl.metadata (2.4 kB)
#0 2.460 Collecting shap>=0.42.1 (from mljar-supervised)
#0 2.466   Downloading shap-0.44.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (24 kB)
#0 2.505 Collecting seaborn>=0.11.1 (from mljar-supervised)
#0 2.510   Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
#0 2.582 Collecting wordcloud>=1.8.1 (from mljar-supervised)
#0 2.587   Downloading wordcloud-1.9.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
#0 2.613 Collecting category_encoders>=2.2.2 (from mljar-supervised)
#0 2.624   Downloading category_encoders-2.6.3-py2.py3-none-any.whl.metadata (8.0 kB)
#0 2.709 Collecting optuna>=2.7.0 (from mljar-supervised)
#0 2.714   Downloading optuna-3.6.1-py3-none-any.whl.metadata (17 kB)
#0 2.746 INFO: pip is looking at multiple versions of mljar-supervised to determine which version is compatible with other requirements. This could take a while.
#0 2.747 Collecting mljar-supervised
#0 2.752   Downloading mljar-supervised-1.1.8.tar.gz (127 kB)
#0 2.798   Preparing metadata (setup.py): started
#0 3.097   Preparing metadata (setup.py): finished with status 'done'
#0 3.106 Collecting mljar-scikit-plot>=0.3.8 (from mljar-supervised)
#0 3.117   Downloading mljar-scikit-plot-0.3.10.tar.gz (25 kB)
#0 3.139   Preparing metadata (setup.py): started
#0 3.332   Preparing metadata (setup.py): finished with status 'error'
#0 3.339   error: subprocess-exited-with-error
#0 3.339   
#0 3.339   × python setup.py egg_info did not run successfully.
#0 3.339   │ exit code: 1
#0 3.339   ╰─> [6 lines of output]
#0 3.339       Traceback (most recent call last):
#0 3.339         File "<string>", line 2, in <module>
#0 3.339         File "<pip-setuptools-caller>", line 34, in <module>
#0 3.339         File "/tmp/pip-install-gq9olotk/mljar-scikit-plot_ddca47a3e5b3486eb05e8139f91ea0d8/setup.py", line 3, in <module>
#0 3.339           from setuptools.command.test import test as TestCommand
#0 3.339       ModuleNotFoundError: No module named 'setuptools.command.test'
#0 3.339       [end of output]
#0 3.339   
#0 3.339   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 3.347 error: metadata-generation-failed
#0 3.347 
#0 3.347 × Encountered error while generating package metadata.
#0 3.347 ╰─> See above for output.
#0 3.347 
#0 3.347 note: This is an issue with the package mentioned above, not pip.
#0 3.347 hint: See above for details.
------
failed to solve: executor failed running [/bin/sh -c pip install mljar-supervised]: exit code: 1

```

**Comment by pplonski** [comment]
I've updated mljar-scikit-plot package.
