### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by klokedm** [mljar/mljar-supervised#770]
Environment:

- MLJar Studio 0.3.1
- Windows 11
- Built-in Python Evnironment

When using the mljar studio I get the error message: "IndexError: list index out of range" with the stack trace:
## Error for 1_Default_LightGBM

list index out of range
Traceback (most recent call last):
  File "\\?\C:\Users\marko\AppData\Roaming\mljar-studio\jlab_server\Lib\site-packages\supervised\base_automl.py", line 1178, in _fit
    trained = self.train_model(params)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\?\C:\Users\marko\AppData\Roaming\mljar-studio\jlab_server\Lib\site-packages\supervised\base_automl.py", line 384, in train_model
    mf.train(results_path, model_subpath)
  File "\\?\C:\Users\marko\AppData\Roaming\mljar-studio\jlab_server\Lib\site-packages\supervised\model_framework.py", line 192, in train
    ].fit_and_transform(
      ^^^^^^^^^^^^^^^^^^
  File "\\?\C:\Users\marko\AppData\Roaming\mljar-studio\jlab_server\Lib\site-packages\supervised\preprocessing\preprocessing.py", line 175, in fit_and_transform
    missing.fit(X_train)
  File "\\?\C:\Users\marko\AppData\Roaming\mljar-studio\jlab_server\Lib\site-packages\supervised\preprocessing\preprocessing_missing.py", line 26, in fit
    X = self._fit_na_fill(X)
        ^^^^^^^^^^^^^^^^^^^^
  File "\\?\C:\Users\marko\AppData\Roaming\mljar-studio\jlab_server\Lib\site-packages\supervised\preprocessing\preprocessing_missing.py", line 32, in _fit_na_fill
    self._na_fill_params[column] = self._get_fill_value(X[column])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\?\C:\Users\marko\AppData\Roaming\mljar-studio\jlab_server\Lib\site-packages\supervised\preprocessing\preprocessing_missing.py", line 43, in _get_fill_value
    return PreprocessingUtils.get_most_frequent(x)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\?\C:\Users\marko\AppData\Roaming\mljar-studio\jlab_server\Lib\site-packages\supervised\preprocessing\preprocessing_utils.py", line 114, in get_most_frequent
    first = sorted(dict(a).items(), key=lambda x: -x[1])[0]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^

**Comment by vivek41-glitch** [comment]
Hi! I'd like to work on this bug.

The root cause is in `preprocessing_utils.py` — `get_most_frequent()` crashes when the sorted list is empty. I'll add a guard check to handle this case gracefully.
